services:
  - type: web
    name: interview-review
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      PYTHON_VERSION: 3.10.0
